### ISSUE TITLE
Python Server Crash takes down Simulator

### ISSUE THREAD

**Issue by dforegger** [house-of-enlightenment/house-of-enlightenment#21]
Can reproduce by running the hoe/houseOfEnlightenment script and doing ctrl-c.

Forwarding OPC input from port 7890 to 3030
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)
server stopped with code 1

**Comment by lax4mike** [comment]
@dforegger did reinstalling `node_modules` fix this for you?

**Comment by dforegger** [comment]
Doesn't appear so. I did gulp simulator:build and then ran it and it still
crashed. (To be fair, first I did gulp simulator:server, then I did build
and server again, cause I forgot a step)

**Comment by lax4mike** [comment]
I can't reproduce on my machine, so we'll have to check out your computer next time
